# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

In [68]:
import numpy as np

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [69]:
val=np.ones((5,5))
arr=np.pad(val, pad_width=1, mode='constant', constant_values=0)
print(arr)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [70]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [71]:

val=np.diag(1+np.arange(4), k=-1)
print(val)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [72]:
val=np.zeros((8, 8), dtype=int)
val[1::2,::2] = 1
val[::2, 1::2]=1
print(val)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [73]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [74]:
val=np.array([[0,1], [1,0]])
checkboard=np.tile(val,(4,4))
print(checkboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [75]:
val=np.random.random((5,5))
valmax, valmin=val.min(), val.max()
val=(val-valmin)/(valmax-valmin)

print(val)

[[ 0.66911297  0.79499079  0.07262003  0.71855762  0.52245344]
 [ 1.          0.68930681  0.20831913 -0.          0.73530782]
 [ 0.764174    0.28069944  0.89651342  0.12368833  0.12171597]
 [ 0.29651611  0.25314366  0.85254573  0.83578125  0.19704798]
 [ 0.29910297  0.67819994  0.94771936  0.32651165  0.60554179]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [76]:
color=np.dtype([("r", np.ubyte,1 ),("g", np.ubyte,1),("b", np.ubyte,1),("a", np.ubyte,1)])

C:\Users\USER\AppData\Local\Temp\ipykernel_15728\2455018866.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color=np.dtype([("r", np.ubyte,1 ),("g", np.ubyte,1),("b", np.ubyte,1),("a", np.ubyte,1)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [77]:
arr1=np.random.random((5,3))
arr2=np.random.random((3,2))
matrix_prod=np.dot(arr1, arr2)
print(matrix_prod)

[[0.60935135 0.3099248 ]
 [0.81106785 0.46822053]
 [0.84748653 0.34767798]
 [0.69639426 0.35850821]
 [0.83724305 0.6465144 ]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [78]:
val=np.arange(11)
val[(3<val)&(val<=8)] *= -1
print(val)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [79]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [80]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\USER\AppData\Local\Temp\ipykernel_15728\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\USER\AppData\Local\Temp\ipykernel_15728\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\USER\AppData\Local\Temp\ipykernel_15728\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [81]:
val=np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(val)), val))

[ 7. 10. -8.  4. -3.  5.  8.  3.  8.  3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [84]:
arr1 = np.random.randint(0,10,10)
arr2= np.random.randint(0,10,10)
print(np.intersect1d(arr1,arr2))

[0 2 3]
